/**
 * Checked accessors for the reference fixture JSON.
 *
 * The fixtures are generated by `experiments/reference/scripts/` and their keys
 * are snake_case, so they are read once through these helpers and handed on as
 * camelCase values. Reading them this way rather than declaring a snake_case
 * interface keeps the naming convention intact and turns a fixture that lost a
 * field into a named error instead of an `undefined` that surfaces as `NaN`
 * three modules later.
 */

/**
 * Narrow an unknown value to a plain record.
 * @param value - The value to narrow.
 * @param label - What the value was supposed to be, for the error message.
 * @returns The value as a record.
 */
export function asRecord(
  value: unknown,
  label: string,
): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new TypeError(`${label} is not an object`);
  }
  return value as Record<string, unknown>;
}

/**
 * Read a nested record.
 * @param record - The parent record.
 * @param key - The key to read.
 * @returns The nested record.
 */
export function childRecord(
  record: Record<string, unknown>,
  key: string,
): Record<string, unknown> {
  return asRecord(record[key], key);
}

/**
 * Read a number.
 * @param record - The record to read from.
 * @param key - The key to read.
 * @returns The number.
 */
export function numberAt(record: Record<string, unknown>, key: string): number {
  const value = record[key];
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    throw new TypeError(`${key} is not a finite number`);
  }
  return value;
}

/**
 * Read a string.
 * @param record - The record to read from.
 * @param key - The key to read.
 * @returns The string.
 */
export function stringAt(record: Record<string, unknown>, key: string): string {
  const value = record[key];
  if (typeof value !== 'string') {
    throw new TypeError(`${key} is not a string`);
  }
  return value;
}

/**
 * Read an array of numbers.
 * @param record - The record to read from.
 * @param key - The key to read.
 * @returns The numbers, in the stored order.
 */
export function numberList(
  record: Record<string, unknown>,
  key: string,
): number[] {
  const value = record[key];
  if (!Array.isArray(value)) {
    throw new TypeError(`${key} is not an array`);
  }
  for (let index = 0; index < value.length; index++) {
    const entry: unknown = value[index];
    if (typeof entry !== 'number' || !Number.isFinite(entry)) {
      throw new TypeError(`${key}[${index}] is not a finite number`);
    }
  }
  return value as number[];
}
